// <auto-generated />
namespace BaiTap2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_tabale_product_and_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_tabale_product_and_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100536098_Create_tabale_product_and_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
